/* Product shell. Existing record formats remain owned by index.html. */
(() => {
  'use strict';
  const KEY = 'zk_product_v1';
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths = {
    home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
    chain:'M10 13a5 5 0 0 0 7 .1l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7-.1l-3 3a5 5 0 0 0 7 7l2-2',
    check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-5-5 5 5-5 5',
    calendar:'M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2Zm2-3v6M17 2v6M3 11h18',
    chart:'M4 4v16h17M8 15l4-5 4 2 5-7',book:'M4 3h14a2 2 0 0 1 2 2v16H6a3 3 0 0 1 0-6h14M6 3v12',
    spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',
    wallet:'M3 6h17v15H3V6Zm0 0 14-3v3M16 11h5v5h-5Z',
    sport:'M3 8v8M7 5v14M17 5v14M21 8v8M7 12h10M3 12h4m10 0h4',
    leaf:'M20 3C10 2 3 6 4 13s11 10 16-10ZM4 21 15 10',
    list:'M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1',
    trophy:'M8 3h8v8a4 4 0 0 1-8 0V3ZM8 5H3v3a4 4 0 0 0 5 4m8-7h5v3a4 4 0 0 1-5 4m-4 3v6m-5 0h10',
    clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',
    grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',
    settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2-5h4l1 3 3 1 3 3v4l-3 1-1 3-3 3h-4l-1-3-3-1-3-3v-4l3-1 1-3Z',
    moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',
    down:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',up:'M12 16V4m-5 5 5-5 5 5M4 17v4h16v-4',
    x:'m6 6 12 12M6 18 18 6',water:'M12 2C9 7 5 11 5 15a7 7 0 0 0 14 0c0-4-4-8-7-13Z',
    play:'m8 4 12 8-12 8Z',pause:'M8 4v16M16 4v16',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z',
    trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z'
  };
  const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.spark}"/></svg>`;
  const pages = {
    today:['Bugün','home','Küçük adımlar, sana ait bir gün.'],planner:['Alışkanlıklar','chain','Sürdürebileceğin kadar küçük başla.'],
    tasks:['Görevler','list','Aklındakileri yaz. Önemli olana yer aç.'],routine:['Rutinler','clock','Günün tekrar eden işlerine bir ritim ver.'],
    sport:['Spor','sport','Planla, hareket et, gelişimini gör.'],calorie:['Beslenme','leaf','Öğünlerini, suyu ve günlük dengeni takip et.'],
    monthly:['Aylık görünüm','calendar','Gün gün ilerlemenin tamamını gör.'],yearly:['Yıllık görünüm','chart','Küçük adımların zaman içindeki karşılığı.'],
    journal:['Günlük','book','Kendini dinlemek için birkaç dakika.'],budget:['Bütçe','wallet','Paranın nereye gittiğini bil.'],
    invest:['Yatırım defteri','chart','Varlıklarını ve kararlarının gerekçelerini kaydet.'],events:['Takvim','calendar','Önemli günler ve yaklaşan planlar.'],
    rank:['Seviye','shield','Düzenli emeğinin birikimi.'],achievements:['Başarılar','trophy','Yol boyunca attığın anlamlı adımlar.'],
    ai:['Asistan','spark','Kayıtlarına bak, bir sonraki küçük adımı seç.'],explore:['Keşfet','grid','Hayatının her alanı, kendi yerinde.'],settings:['Ayarlar','settings','Görünümün, hedeflerin ve verilerin senin kontrolünde.']
  };
  const groups = [['Günlük yaşam',['today','planner','tasks','routine']],['İyi yaşam',['sport','calorie','journal']],['Plan & ilerleme',['monthly','budget','invest','explore']]];
  function defaults(){return {version:1,language:ZKI18n.language,theme:'light',water:{},focus:{minutes:25,remaining:1500,running:false,end:null,sessions:[]},portfolio:[],budgetLimits:{},favorites:[],workout:null,workoutGoal:3,workoutPlan:[],journalDraft:{},review:{}};}
  let data;
  try {data=ZKValidation.normalizeProduct(JSON.parse(localStorage.getItem(KEY)||'{}'),defaults());}catch{data=defaults();}
  const Z = window.ZK = {userHTML:value=>'<span translate="no" data-user-content>'+esc(value)+'</span>',KEY,esc,icon,pages,data,actions:{},forms:{},booted:false,
    today:()=>getToday(), uid:()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():'zk_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),
    read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},
    write(){try{localStorage.setItem(KEY,JSON.stringify(Z.data));return true}catch{try{Z.data=ZKValidation.normalizeProduct(JSON.parse(localStorage.getItem(KEY)||'{}'),defaults())}catch{Z.data=defaults()}throw Error('Kayıt saklanamadı. Cihazında yer açıp yeniden dene.')}},
    button(label,action,extra='',kind=''){return `<button class="zk-btn ${kind}" data-zk="${action}" ${extra}>${label}</button>`},
    field(id,label,type='text',value='',extra=''){return `<label class="zk-field">${label}<input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`},
    heading(page,action=''){const p=pages[page];return `<div class="zk-page-heading"><div><h1 tabindex="-1">${p[0]}</h1><p>${p[2]}</p></div>${action}</div>`},
    toast(message,undo){document.getElementById('zk-toast')?.remove();clearTimeout(Z.toastTimer);const e=document.createElement('div');e.id='zk-toast';e.className='zk-toast';e.setAttribute('role','status');e.append(document.createTextNode(message));if(undo){const b=document.createElement('button');b.textContent='Geri al';b.onclick=()=>{undo();e.remove()};e.append(b)}document.body.append(e);Z.toastTimer=setTimeout(()=>e.remove(),undo?10000:4500)},
    dialog(title,html){Z.returnFocus=document.activeElement;const el=document.getElementById('zk-dialog');el.innerHTML=`<div class="zk-dialog-head"><h2 id="zk-dialog-title">${title}</h2><button class="zk-icon-button" data-zk="closeDialog" aria-label="Pencereyi kapat">${icon('x')}</button></div>${html}`;if(!el.open)el.showModal();},
    closeDialog(){document.getElementById('zk-dialog').close();Z.returnFocus?.focus?.()},
    go(page){navigateTo(page)},
    dateLabel(date,options={day:'numeric',month:'short'}){return new Date(date+'T12:00:00').toLocaleDateString(ZKI18n.locale(),options)},
    weekDates(){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return Array.from({length:7},(_,i)=>{const day=new Date(d);day.setDate(day.getDate()+i);return getDayKey(day)})},
    weekStats(){const h=state.habits.filter(h=>h.type!=='quit');const dates=Z.weekDates().filter(d=>d<=getToday());return {done:dates.reduce((n,date)=>n+h.filter(h=>state.completions[date]?.[h.id]===true).length,0),possible:dates.reduce((n,date)=>n+h.filter(h=>!h.createdAt||h.createdAt<=date).length,0)}}
  };
  document.documentElement.dataset.theme=Z.data.theme==='dark'?'dark':'light';
  const nav = (page, cls='zk-nav-item')=>`<button class="${cls}" data-zk="go" data-page="${page}">${icon(pages[page][1])}<span>${pages[page][0]}</span></button>`;
  const oldNavigate=navigateTo;
  navigateTo=function(page){
    if(!Z.booted)return oldNavigate(page in pages&&document.getElementById('page-'+page)?page:'planner');
    if(!pages[page])page='today';
    const changed=state.currentPage!==page;
    oldNavigate(page);
    document.querySelectorAll('.zk-nav-item,.zk-mobile-nav button').forEach(b=>{const active=b.dataset.page===page||(b.dataset.page==='explore'&&!['today','planner','tasks','sport'].includes(page)&&b.closest('.zk-mobile-nav'));b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
    document.getElementById('zk-crumb').textContent=pages[page][0];
    document.title=`${pages[page][0]} · Zinciri Kırma`;
    if(page==='today')Z.renderToday();
    if(page==='explore')Z.renderExplore();
    if(page==='settings')Z.renderSettings();
    Z.enhance?.(page);
    Z.a11y();
    if(changed){window.scrollTo({top:0,behavior:'instant'});document.querySelector(`#page-${page} h1`)?.focus({preventScroll:true})}
  };
  // No demo cloud connection is treated as a working account.
  initFirebase=function(){};autoReconnectSync=function(){};pushToCloud=function(){};
  openSettings=function(){if(Z.booted)Z.go('settings')};
  checkStreakBreak=function(){};checkWeeklyRecap=function(){};
  showConfetti=function(){};
  Z.a11y=function(){
    document.querySelectorAll('input:not([aria-label]):not([type=hidden]),textarea:not([aria-label]),select:not([aria-label])').forEach(el=>{if(el.closest('label')||el.labels?.length)return;el.setAttribute('aria-label',el.placeholder||el.id.replaceAll('-',' ')||'Değer')});
    document.querySelectorAll('button:not([aria-label])').forEach(b=>{if(b.closest('.zk-start'))return;const text=b.textContent.trim();if(!text||text.length<3){const action=b.getAttribute('onclick')||'';b.setAttribute('aria-label',b.title||(/delete|remove/i.test(action)?'Kaydı sil':/close/i.test(action)?'Pencereyi kapat':text==='+'?'Ekle':text||'Seç'))}});
    document.querySelectorAll('.overlay').forEach(el=>{el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');const title=el.querySelector('h2');if(title){title.id ||=el.id+'-title';el.setAttribute('aria-labelledby',title.id)}});
  };
  Z.renderToday=function(){
    loadTasksData();loadCalorieData();loadSportData();loadRoutine();
    const today=getToday(),habits=state.habits.filter(h=>h.type!=='quit'),done=habits.filter(h=>state.completions[today]?.[h.id]===true).length;
    const tasks=tasksData.tasks.filter(t=>t.date===today),pending=tasks.filter(t=>!t.done).sort((a,b)=>({urgent:0,important:1,normal:2}[a.priority]??2)-({urgent:0,important:1,normal:2}[b.priority]??2));
    const ws=Z.weekStats(),streak=getOverallStreak(),water=Z.data.water[today]||0,logs=getTodayLogs();
    const dayList=Z.weekDates().map((date,i)=>{const eligible=habits.filter(h=>!h.createdAt||h.createdAt<=date),n=eligible.filter(h=>state.completions[date]?.[h.id]===true).length,full=eligible.length>0&&n===eligible.length;return `<div class="zk-day ${full?'done':''} ${date===today?'today':''} ${date>today?'future':''}" aria-label="${Z.dateLabel(date)}: ${date>today?'gelecek gün':n+' / '+eligible.length+' alışkanlık'}"><div class="zk-day-square">${full?icon('check'):new Date(date+'T12:00:00').getDate()}</div><small>${['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][i]}</small></div>`}).join('');
    document.getElementById('page-today').innerHTML=`
      <div class="zk-page-heading"><div><h1 tabindex="-1">${new Date().getHours()<12?'Günaydın':new Date().getHours()<18?'Merhaba':'İyi akşamlar'}, <span translate="no" data-user-content>${esc(state.user.name||ZKI18n.t('arkadaşım'))}</span><span style="color:var(--accent)">.</span></h1><p>Bugün kendin için küçük bir şey yap.</p></div>${Z.button(icon('plus')+' Alışkanlık','newHabit','','primary')}</div>
      <section class="zk-week" aria-label="Bu haftaki alışkanlık zinciri"><div><h2>${streak>0?streak+' gündür devam ediyorsun.':'Her gün, yeni bir halka.'}</h2><p>${done===habits.length&&habits.length?'Bugünün alışkanlıkları tamam. Kendine zaman ayır.':'Kusursuz olmak zorunda değilsin. Bugün burada olman iyi bir başlangıç.'}</p></div><div class="zk-days">${dayList}</div></section>
      <div class="zk-columns"><div class="zk-stack"><section class="zk-panel"><div class="zk-section-head"><h2>Bugünün alışkanlıkları</h2><span class="zk-chip green">${done} / ${habits.length} tamamlandı</span></div><div>${habits.length?habits.map(h=>Z.habitRow(h,today)).join(''):`<div class="zk-empty"><h3>İlk halkanı oluştur.</h3><p>Bir sayfa okumak, kısa bir yürüyüş veya sadece günü planlamak. Sana uyan bir adım seç.</p>${Z.button('İlk alışkanlığını ekle '+icon('arrow'),'newHabit','','primary')}</div>`}</div>${habits.length?`<div class="zk-progress" role="progressbar" aria-label="Bugünün alışkanlıkları" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${habits.length}"><span style="width:${done/habits.length*100}%"></span></div><div class="zk-week-footer">${icon('chain')} Bu hafta ${ws.done} kez kendin için adım attın.</div>`:''}</section>
      <section class="zk-panel"><div class="zk-section-head"><h2>Önce bunlara odaklan</h2><button class="zk-link" data-zk="go" data-page="tasks">Tüm görevler ${icon('arrow')}</button></div>${pending.length?pending.slice(0,3).map(t=>`<div class="zk-row"><button class="zk-check" data-zk="taskDone" data-id="${esc(t.id)}" aria-label="${esc(t.text)} ${ZKI18n.t('tamamlandı')}" aria-pressed="false">${icon('check')}</button><div class="zk-row-body"><strong><span translate="no" data-user-content>${esc(t.text)}</span></strong><small>${({urgent:'Öncelikli',important:'Önemli',normal:'Bugün'})[t.priority]||'Bugün'}</small></div></div>`).join(''):`<p class="zk-muted">${tasks.length?'Bugünkü görevlerini tamamladın.':'Bugün bitirmek istediğin tek bir işle başla.'}</p>`}<form class="zk-inline-form" data-zk-form="quickTask"><input name="task" maxlength="200" required placeholder="Aklındaki bir işi yaz…" aria-label="Yeni günlük görev"><button class="zk-icon-button" type="submit" aria-label="Görevi ekle">${icon('plus')}</button></form></section></div>
      <aside class="zk-stack">${Z.focusMarkup()}<section class="zk-panel"><div class="zk-section-head"><h2>Gününe bir bakış</h2>${icon('leaf')}</div><div class="zk-summary-row"><span>Antrenman</span><strong>${sportData.sessions.filter(s=>s.date===today).length?'Kaydedildi':'Henüz kayıt yok'}</strong></div><div class="zk-summary-row"><span>Beslenme</span><strong>${logs.length?getTodayTotal().toLocaleString(ZKI18n.locale())+' kcal':'Öğün ekle'}</strong></div><div class="zk-summary-row"><span>Su</span><strong>${(water/1000).toLocaleString(ZKI18n.locale())} L</strong></div><div class="zk-summary-row"><span>Günlük görevler</span><strong>${tasks.filter(t=>t.done).length} / ${tasks.length}</strong></div><div class="zk-module-links"><button class="zk-module-link" data-zk="go" data-page="sport">${icon('sport')} Spor</button><button class="zk-module-link" data-zk="go" data-page="calorie">${icon('leaf')} Öğün</button><button class="zk-module-link" data-zk="go" data-page="journal">${icon('book')} Günlük</button></div></section></aside></div><p class="zk-bottom-copy">Büyük değişimler, tekrar ettiğin küçük şeylerden doğar.</p>`;
    Z.tickFocus();
  };
  Z.habitRow=function(h,date){const complete=state.completions[date]?.[h.id]===true;return `<div class="zk-row zk-habit ${complete?'done':''}"><button class="zk-check" data-zk="habitDone" data-id="${esc(h.id)}" aria-label="${esc(h.name)}" aria-pressed="${complete}">${icon('check')}</button><div class="zk-row-body"><strong><span translate="no" data-user-content>${esc(h.name)}</span></strong><small>${h.target||30} gün / ay · ${complete?'Bugün tamamlandı':'Kendine verdiğin küçük söz'}</small></div><span class="zk-habit-count">${getHabitStreak(h.id)||0} gün seri</span></div>`};
  Z.focusMarkup=function(){const f=Z.data.focus;return `<section class="zk-focus"><h2>Biraz odak, iyi gelir.</h2><p>Bir iş seç. Bildirimleri sessize al. Başla.</p><div class="zk-focus-controls">${[15,25,45].map(m=>`<button data-zk="focusLength" data-minutes="${m}" aria-pressed="${f.minutes===m}" ${f.running?'disabled':''}>${m} dk</button>`).join('')}</div><div class="zk-timer" data-focus-clock>25:00</div><div class="zk-actions"><button class="zk-btn mint" data-zk="focusToggle" data-focus-toggle>${icon(f.running?'pause':'play')}${f.running?'Duraklat':'Odaklanmaya başla'}</button><button class="zk-btn" data-zk="focusReset" aria-label="Odak sayacını sıfırla">Sıfırla</button></div><p>${f.sessions.filter(s=>s.date===getToday()).length} odak oturumu bugün tamamlandı</p></section>`};
  Z.tickFocus=function(){const f=Z.data.focus;if(f.running){f.remaining=Math.max(0,Math.ceil((f.end-Date.now())/1000));if(!f.remaining){f.running=false;f.end=null;f.sessions.push({id:Z.uid(),date:getToday(),minutes:f.minutes});Z.write();Z.toast('Odak oturumun tamamlandı. Kısa bir mola ver.');if(state.currentPage==='today')Z.renderToday();else if(state.currentPage==='tasks')Z.enhance('tasks')}}document.querySelectorAll('[data-focus-clock]').forEach(el=>{el.textContent=Math.floor(f.remaining/60)+':'+String(f.remaining%60).padStart(2,'0')})};
  Z.renderExplore=function(filter=''){const list=[['Günlük yaşam',['planner','tasks','routine','events','journal']],['İyi yaşam',['sport','calorie']],['Para & kararlar',['budget','invest']],['İlerleme & araçlar',['monthly','yearly','rank','achievements','ai','settings']]];const el=document.getElementById('page-explore');if(!document.getElementById('zk-explore-list'))el.innerHTML=Z.heading('explore')+`<label class="zk-field">Bölüm ara<input id="zk-explore-search" type="search" placeholder="Spor, bütçe, günlük…"></label><div id="zk-explore-list" class="zk-explore-grid" style="margin-top:28px"></div>`;let count=0;document.getElementById('zk-explore-list').innerHTML=list.map(([title,ps])=>{const found=ps.filter(p=>(ZKI18n.t(pages[p][0])+' '+ZKI18n.t(pages[p][2])+' '+pages[p][0]).toLocaleLowerCase(ZKI18n.locale()).includes(filter.toLocaleLowerCase(ZKI18n.locale())));count+=found.length;return found.length?`<section class="zk-explore-group"><h2>${title}</h2>${found.map(p=>`<button class="zk-explore-item" data-zk="go" data-page="${p}">${icon(pages[p][1])}<div><strong>${pages[p][0]}</strong><small>${pages[p][2]}</small></div>${icon('arrow')}</button>`).join('')}</section>`:''}).join('')||'<p class="zk-muted">Eşleşen bölüm yok. Daha kısa bir kelime dene.</p>'};
  Z.showStart=function(){const el=document.createElement('section');el.className='zk-start';el.id='zk-start';el.setAttribute('aria-label','Hoş geldin');el.innerHTML=`<div class="zk-start-inner"><div class="zk-start-brand"><div class="zk-logo"><span class="zk-logo-mark">${icon('chain')}</span>zinciri kırma</div><h1>Küçük adımlar.<br>Sana ait bir hayat.</h1><p>Alışkanlıkların, hareketin ve günlük planın. Her şeyi yetiştirmek için değil, sana iyi geleni sürdürmek için.</p><div class="zk-start-art" aria-hidden="true"><span>${icon('check')}</span><span>${icon('check')}</span><span>${icon('check')}</span><span>${icon('plus')}</span></div></div><form class="zk-start-form zk-form" data-zk-form="start">${ZKI18n.picker()}<div><h2>Bugünden başlayalım.</h2><p class="zk-muted">Bir isim, bir küçük adım. Hepsi bu.</p></div>${Z.field('zk-name','Sana nasıl hitap edelim?','text','','maxlength="30" autocomplete="given-name" placeholder="Adın veya takma adın"')}<div><p class="zk-note">İstersen ilk alışkanlıklarını seç:</p><div class="zk-stack" style="gap:9px">${['10 dakika kitap oku','Kısa bir yürüyüş yap','Günün en önemli işini seç'].map((name,i)=>`<label class="zk-start-choice"><input type="checkbox" name="habit" value="${esc(name)}" ${i===0?'checked':''}>${name}</label>`).join('')}</div></div><button class="zk-btn primary" type="submit">Kendi ritmini kur ${icon('arrow')}</button><p class="zk-start-privacy">Hesap gerekmez. Kayıtların bu cihazda saklanır.<br>Seçimlerini istediğin zaman değiştirebilirsin.</p><button class="zk-link" type="button" data-zk="startEmpty">Önce uygulamayı keşfet ${icon('arrow')}</button></form></div>`;document.body.append(el)};
  Z.start=function(name,habits){const today=getToday(),end=new Date();end.setFullYear(end.getFullYear()+1);state.user={name:name||ZKI18n.t('Misafir'),startDate:today,endDate:getDayKey(end),template:'custom'};state.habits=habits.map(name=>({id:Z.uid(),name,emoji:'✓',color:'#1d7154',target:20,type:'good',createdAt:today}));state.currentPage='today';try{Z.data.language=ZKI18n.language;Z.write();saveState()}catch{Z.toast('Başlangıç saklanamadı. Cihazındaki depolama ayarlarını kontrol et.');return}document.getElementById('zk-start')?.remove();document.getElementById('app').classList.remove('hidden');document.getElementById('onboarding-overlay').classList.add('hidden');Z.updateProfile();Z.go('today')};
  Z.updateProfile=function(){const name=state.user.name||'Misafir';document.getElementById('zk-profile').textContent=name.slice(0,1).toLocaleUpperCase('tr');document.getElementById('zk-profile').setAttribute('aria-label',name+' için ayarlar')};
  Z.renderSettings=function(){document.getElementById('page-settings').innerHTML=Z.heading('settings')+`<div class="zk-two"><section class="zk-panel"><h2>Sana göre</h2><form class="zk-form" data-zk-form="profile" style="margin-top:22px">${Z.field('zk-profile-name','Görünür adın','text',state.user.name,'required maxlength="30"')}${ZKI18n.picker()}<p class="zk-note">Dil tercihin bu cihazda saklanır. Kendi yazdığın kayıtlar çevrilmez.</p><label class="zk-field">Görünüm<select name="theme"><option value="light" ${Z.data.theme==='light'?'selected':''}>Açık · Gün ışığı</option><option value="dark" ${Z.data.theme==='dark'?'selected':''}>Koyu · Akşam</option></select></label>${Z.field('zk-workout-goal','Haftalık antrenman hedefin','number',Z.data.workoutGoal,'min="1" max="7" required')}<button class="zk-btn primary" type="submit">Tercihleri kaydet</button></form><p class="zk-note">Bu sayı senin takip hedefindir; sana özel bir antrenman önerisi değildir.</p></section><section class="zk-panel"><h2>Verilerin sende</h2><p class="zk-muted" style="margin-top:10px">Alışkanlıklar, spor, öğünler, rutinler, görevler ve finans kayıtlarını tek dosyada yedekle.</p><div class="zk-actions">${Z.button(icon('down')+' Tam yedek indir','backup','','primary')}${Z.button(icon('up')+' Yedeği geri yükle','restore')}</div><input type="file" id="zk-backup-input" accept=".json,application/json" hidden><p class="zk-note">Son yedek: ${Z.data.lastBackup?new Date(Z.data.lastBackup).toLocaleString(ZKI18n.locale()):'Henüz alınmadı'}</p><hr class="zk-rule"><h3>Cihazda saklama</h3><p class="zk-note">Tarayıcı verilerini temizlemek veya uygulamayı kaldırmak kayıtlarını silebilir. Başka cihaza geçmeden önce yedeğini indir. Bu sürümde bulut senkronizasyonu etkin değildir.</p>${Z.button('Veri ve gizlilik bilgisi','privacy')}<hr class="zk-rule"><h3>Uygulamayı yükle</h3><p class="zk-note">Destekleyen tarayıcılarda ana ekranına ekleyebilir, ilk açılıştan sonra temel takibi çevrimdışı kullanabilirsin.</p>${Z.button('Ana ekrana ekle','install')}</section></div><section class="zk-panel" style="margin-top:24px"><h2>Yardım & geri bildirim</h2><p class="zk-note">Bir sorun bildirirken kişisel kayıtlarını paylaşmana gerek yok. Hangi bölümde ne yaparken karşılaştığını ve cihazını not et.</p>${Z.button('Teknik bilgileri kopyala','diagnostics')}<p class="zk-note">Zinciri Kırma · ürün önizlemesi 1.0.0</p></section>`};
  const allowedKey = key=>/^(zinciriKirma|zk_)/.test(key)&&!/(api|token|secret|syncCode|password)/i.test(key);
  Z.backupData=()=>Object.fromEntries(Object.keys(localStorage).filter(allowedKey).map(k=>[k,localStorage.getItem(k)]));
  Z.download=function(object,name){const url=URL.createObjectURL(new Blob([JSON.stringify(object,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)};
  Z.validateBackup=function(parsed){if(parsed?.format!=='zinciri-kirma-full'||parsed.version!==1||!parsed.records||Array.isArray(parsed.records))throw Error('Bu dosya tam uygulama yedeği değil.');for(const [k,v] of Object.entries(parsed.records)){if(!allowedKey(k)||typeof v!=='string')throw Error('Desteklenmeyen kayıt bulundu.');if(k===KEY)ZKValidation.normalizeProduct(JSON.parse(v),defaults());if(k!=='zk_product_v1'&&/^(zinciriKirma2026$|zinciriKirma(?:Sport|Tasks|Routine|Calorie|Invest|Budget|Events)2026$)/.test(k))ZKValidation.validateLegacy(k,v);if(k==='zinciriKirma2026'){const s=JSON.parse(v);if(!s.user||typeof s.user.name!=='string'||!Array.isArray(s.habits)||!s.completions||!Array.isArray(s.journal)||!Array.isArray(s.achievements)||s.habits.some(h=>typeof h.id!=='string'||typeof h.name!=='string'))throw Error('Alışkanlık yedeği eksik.')}if(/Sport2026$/.test(k)){const s=JSON.parse(v);if(!['sessions','swim','cardio','measurements'].every(a=>Array.isArray(s[a]))||s.sessions.some(t=>typeof t.date!=='string'||!Array.isArray(t.exercises)))throw Error('Spor yedeği eksik.')}if(/(Calorie2026|Invest2026|Budget2026|Events2026)$/.test(k)&&!Array.isArray(JSON.parse(v)))throw Error('Kayıt listesi geçersiz.');if(/Tasks2026$/.test(k)&&!Array.isArray(JSON.parse(v).tasks))throw Error('Görev yedeği eksik.');if(/Routine2026$/.test(k)&&!Array.isArray(JSON.parse(v).tasks))throw Error('Rutin yedeği eksik.');if(k===KEY){const d=JSON.parse(v);if(d.version!==1||!Array.isArray(d.portfolio)||!d.focus||!Array.isArray(d.focus.sessions)||!d.water)throw Error('Ürün ayarları geçersiz.')}}if(!parsed.records.zinciriKirma2026)throw Error('Ana kayıt bulunamadı.');return parsed.records};
  Z.applyBackup=function(records){const before=Z.backupData();try{Object.keys(localStorage).filter(allowedKey).forEach(k=>localStorage.removeItem(k));Object.entries(records).forEach(([k,v])=>localStorage.setItem(k,v))}catch(e){Object.keys(localStorage).filter(allowedKey).forEach(k=>localStorage.removeItem(k));Object.entries(before).forEach(([k,v])=>localStorage.setItem(k,v));throw e}};
  Object.assign(Z.actions,{
    go:b=>Z.go(b.dataset.page),closeDialog:()=>Z.closeDialog(),startEmpty:()=>Z.start(ZKI18n.t('Misafir'),[]),
    theme:()=>{Z.data.theme=Z.data.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=Z.data.theme;Z.write();if(state.currentPage==='settings')Z.renderSettings()},
    newHabit:()=>Z.dialog('Küçük bir adım seç',`<form class="zk-form" data-zk-form="habit">${Z.field('zk-habit-name','Ne yapmak istiyorsun?','text','','required maxlength="100" placeholder="Örn. 10 dakika kitap oku"')}${Z.field('zk-habit-target','Ayda kaç gün?','number',20,'required min="1" max="31"')}<p class="zk-note">Gerçekçi bir hedef seç. Dinlenmeye ve yoğun günlere yer bırakabilirsin.</p><button class="zk-btn primary" type="submit">Alışkanlığı ekle</button></form>`),
    habitDone:b=>{const date=getToday(),id=b.dataset.id;toggleCompletion(id,date);if(state.completions[date]?.[id])Z.toast('Bir küçük adım daha tamam.')},
    taskDone:b=>{toggleTask(b.dataset.id);Z.renderToday()},
    focusLength:b=>{const f=Z.data.focus;if(f.running)return;f.minutes=+b.dataset.minutes;f.remaining=f.minutes*60;Z.write();if(state.currentPage==='today')Z.renderToday();else Z.enhance('tasks')},
    focusToggle:()=>{const f=Z.data.focus;if(f.running){f.remaining=Math.max(0,Math.ceil((f.end-Date.now())/1000));f.running=false;f.end=null}else{if(!f.remaining)f.remaining=f.minutes*60;f.end=Date.now()+f.remaining*1000;f.running=true}Z.write();if(state.currentPage==='today')Z.renderToday();else Z.enhance('tasks')},
    focusReset:()=>{const f=Z.data.focus;f.running=false;f.end=null;f.remaining=f.minutes*60;Z.write();if(state.currentPage==='today')Z.renderToday();else Z.enhance('tasks')},
    backup:()=>{Z.data.lastBackup=new Date().toISOString();Z.write();Z.download({format:'zinciri-kirma-full',version:1,exportedAt:new Date().toISOString(),records:Z.backupData()},'zinciri-kirma-tam-yedek-'+getToday()+'.json');if(state.currentPage==='settings')Z.renderSettings();Z.toast('Tam yedek dosyan hazır.')},
    restore:()=>document.getElementById('zk-backup-input').click(),
    confirmRestore:()=>{try{Z.applyBackup(Z.pendingRestore);Z.pendingRestore=null;location.reload()}catch{Z.closeDialog();Z.toast('Yedek yüklenemedi. Mevcut kayıtların geri alındı.')}},
    privacy:()=>Z.dialog('Veri ve gizlilik',`<div class="zk-form"><p>Bu sürümde kayıtların bu cihazın tarayıcı alanında saklanır. Tam yedek dosyası sağlık ve finans kayıtlarını içerebilir; yalnızca güvendiğin yerde tut.</p><p>Bulut senkronizasyonu, reklam ve analiz hizmeti bu sürümde etkin değildir. Eski asistan ve fotoğraf analizi bağlantıları ürün sürümünde kapalıdır.</p><p>Uygulamayı başka bir adres veya tarayıcıda açarsan farklı bir veri alanı kullanılır. Kayıtlarını taşımak için tam yedek alıp yeni yerde geri yükle.</p><p>Bu araç tıbbi değerlendirme veya kişiye özel yatırım tavsiyesi sunmaz.</p>${Z.button('Anladım','closeDialog','','primary')}</div>`),
    install:async()=>{if(Z.installPrompt){await Z.installPrompt.prompt();const choice=await Z.installPrompt.userChoice;Z.installPrompt=null;Z.toast(choice.outcome==='accepted'?'Uygulama yükleme isteği alındı.':'İstersen daha sonra yükleyebilirsin.')}else Z.dialog('Ana ekranına ekle',`<div class="zk-form"><p><strong>iPhone / iPad:</strong> Safari’de Paylaş menüsünden “Ana Ekrana Ekle” seçeneğini kullan.</p><p><strong>Android:</strong> Chrome menüsünde “Uygulamayı yükle” veya “Ana ekrana ekle” seçeneğini bul.</p><p class="zk-note">Yükleme için uygulamanın HTTPS adresinden veya localhost üzerinden açılması gerekir. Doğrudan HTML dosyasında çevrimdışı kurulum desteklenmez.</p>${Z.button('Tamam','closeDialog','','primary')}</div>`)},
    diagnostics:async()=>{const info='Zinciri Kırma 1.0.0\n'+navigator.userAgent+'\nEkran: '+innerWidth+' × '+innerHeight;try{await navigator.clipboard.writeText(info);Z.toast('Teknik bilgiler kopyalandı.')}catch{Z.dialog('Teknik bilgiler',`<textarea readonly rows="5" aria-label="Kopyalanabilir teknik bilgiler">${esc(info)}</textarea>`)}}
  });
  Object.assign(Z.forms,{
    start:form=>Z.start(form.elements['zk-name'].value.trim(),[...form.querySelectorAll('input[name=habit]:checked')].map(e=>ZKI18n.t(e.value))),
    quickTask:form=>{const text=form.elements.task.value.trim();if(!text)return;loadTasksData();tasksData.tasks.unshift({id:Z.uid(),text,date:getToday(),priority:'normal',done:false});saveTasksData();Z.renderToday()},
    habit:form=>{const name=form.elements['zk-habit-name'].value.trim();if(!name)return;state.habits.push({id:Z.uid(),name,emoji:'✓',color:'#1d7154',target:+form.elements['zk-habit-target'].value,type:'good',createdAt:getToday()});saveState();Z.closeDialog();Z.go(state.currentPage);Z.toast('Alışkanlığın eklendi.')},
    profile:form=>{state.user.name=form.elements['zk-profile-name'].value.trim()||'Misafir';Z.data.theme=form.elements.theme.value;Z.data.workoutGoal=+form.elements['zk-workout-goal'].value;saveState();Z.write();document.documentElement.dataset.theme=Z.data.theme;Z.updateProfile();ZKI18n.setLanguage(form.elements.language.value);Z.renderSettings();Z.toast(ZKI18n.t('Tercihlerin kaydedildi.'))}
  });
  document.addEventListener('click',e=>{const b=e.target.closest('[data-zk]');if(!b)return;const fn=Z.actions[b.dataset.zk];if(fn){e.preventDefault();try{const result=fn(b);if(result?.catch)result.catch(()=>Z.toast('İşlem tamamlanamadı. Tekrar dene.'))}catch(error){console.error(error);Z.toast(error.message||'İşlem tamamlanamadı. Tekrar dene.')}}});
  document.addEventListener('submit',e=>{const form=e.target;if(!form.dataset.zkForm)return;e.preventDefault();if(!form.reportValidity())return;try{Z.forms[form.dataset.zkForm]?.(form)}catch(error){console.error(error);Z.toast(error.message||'Kayıt tamamlanamadı. Değerlerini kontrol edip tekrar dene.')}});
  document.addEventListener('input',e=>{if(e.target.id==='zk-explore-search')Z.renderExplore(e.target.value)});
  document.addEventListener('change',async e=>{if(e.target.id!=='zk-backup-input')return;const file=e.target.files[0];if(!file)return;try{if(file.size>25*1024*1024)throw Error('Yedek 25 MB sınırını aşıyor.');const records=Z.validateBackup(JSON.parse(await file.text()));Z.pendingRestore=records;Z.dialog('Yedeği geri yükle',`<p>${Object.keys(records).length} veri bölümü doğrulandı. Bu işlem mevcut kayıtlarının yerine seçtiğin yedeği koyar.</p><p class="zk-note">Devam etmeden önce mevcut verilerini de yedeklemeni öneririz.</p><div class="zk-actions">${Z.button('Vazgeç','closeDialog')}${Z.button('Yedeği uygula','confirmRestore','','primary')}</div>`)}catch(error){Z.toast(error.message||'Yedek okunamadı.')}finally{e.target.value=''}});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();Z.installPrompt=e});
  document.addEventListener('DOMContentLoaded',()=>{
    const app=document.getElementById('app');
    app.insertAdjacentHTML('afterbegin',`<aside class="zk-rail"><div class="zk-logo"><span class="zk-logo-mark">${icon('chain')}</span>zinciri kırma</div><nav aria-label="Ana gezinme">${groups.map(([title,ps])=>`<div class="zk-nav-group"><div class="zk-nav-caption">${title}</div>${ps.map(p=>nav(p)).join('')}</div>`).join('')}</nav><div class="zk-rail-bottom">${nav('settings')}<p class="zk-rail-note">Her gün, kendin için.</p></div></aside><header class="zk-top"><span class="zk-top-crumb" id="zk-crumb">Bugün</span><div class="zk-top-actions"><span class="zk-top-date">${new Date().toLocaleDateString(ZKI18n.locale(),{day:'numeric',month:'long',year:'numeric'})}</span><button class="zk-icon-button" data-zk="theme" aria-label="Açık ve koyu görünüm arasında geçiş yap">${icon('moon')}</button><button class="zk-icon-button" data-zk="go" data-page="explore" aria-label="Bölüm ara">${icon('search')}</button><button class="zk-profile" id="zk-profile" data-zk="go" data-page="settings">M</button></div></header>`);
    ['today','explore','settings'].forEach(page=>{const el=document.createElement('section');el.id='page-'+page;el.className='page hidden';app.append(el)});
    Object.keys(pages).filter(p=>!['today','explore','settings'].includes(p)).forEach(p=>{const el=document.getElementById('page-'+p);if(el)el.insertAdjacentHTML('afterbegin',Z.heading(p))});
    app.insertAdjacentHTML('beforeend',`<nav class="zk-mobile-nav" aria-label="Ana gezinme">${['today','planner','tasks','sport','explore'].map(p=>nav(p,'')).join('')}</nav>`);
    document.body.insertAdjacentHTML('beforeend','<dialog id="zk-dialog" class="zk-dialog" aria-labelledby="zk-dialog-title"></dialog>');
    document.getElementById('zk-dialog').addEventListener('click',e=>{if(e.target.id==='zk-dialog'){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)Z.closeDialog()}});
    document.getElementById('onboarding-overlay').classList.add('hidden');
    Z.booted=true;Z.updateProfile();Z.setupModules?.();
    if(state.user.name){app.classList.remove('hidden');Z.go('today')}else Z.showStart();
    Z.a11y();setInterval(()=>{Z.tickFocus();Z.tickWorkout?.()},1000);
    let lastDay=getToday();document.addEventListener('visibilitychange',()=>{if(!document.hidden){Z.tickFocus();if(lastDay!==getToday()){lastDay=getToday();Z.go(state.currentPage)}}});
    if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
  });
})();
